import { AlertSeverity,AlertStatus,CommandStatus,MaintenanceStatus,TaskStatus } from "@prisma/client";
import { IsBoolean,IsDateString,IsEnum,IsInt,IsNumber,IsObject,IsOptional,IsString,Max,Min } from "class-validator";
export class GeofenceDto { @IsString() name!:string; @IsString() type!:string; @IsObject() geometry!:Record<string,unknown>; @IsOptional() @IsString() color?:string; @IsOptional() @IsBoolean() active?:boolean; }
export class AlertDto { @IsOptional() @IsString() vehicleId?:string; @IsString() type!:string; @IsString() title!:string; @IsString() message!:string; @IsOptional() @IsEnum(AlertSeverity) severity?:AlertSeverity; @IsOptional() metadata?:Record<string,unknown>; }
export class AlertStatusDto { @IsEnum(AlertStatus) status!:AlertStatus; }
export class MaintenanceDto { @IsString() vehicleId!:string; @IsString() name!:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsEnum(MaintenanceStatus) status?:MaintenanceStatus; @IsOptional() @IsNumber() intervalKm?:number; @IsOptional() @IsNumber() intervalHours?:number; @IsOptional() @IsDateString() dueAt?:string; @IsOptional() @IsNumber() dueOdometer?:number; @IsOptional() @IsNumber() cost?:number; }
export class FuelDto { @IsString() vehicleId!:string; @IsNumber() @Min(0.01) liters!:number; @IsOptional() @IsNumber() pricePerLiter?:number; @IsOptional() @IsNumber() totalCost?:number; @IsOptional() @IsNumber() odometer?:number; @IsOptional() @IsString() station?:string; @IsDateString() filledAt!:string; }
export class TaskDto { @IsString() title!:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsString() vehicleId?:string; @IsOptional() @IsEnum(TaskStatus) status?:TaskStatus; @IsOptional() @IsInt() @Min(1) @Max(4) priority?:number; @IsOptional() @IsDateString() startsAt?:string; @IsOptional() @IsDateString() dueAt?:string; }
export class UserDto { @IsString() name!:string; @IsString() email!:string; @IsString() password!:string; @IsString() role!:string; @IsOptional() @IsBoolean() active?:boolean; }
export class CommandDto { @IsString() vehicleId!:string; @IsString() type!:string; @IsOptional() @IsObject() payload?:Record<string,unknown>; }
export class CommandStatusDto { @IsEnum(CommandStatus) status!:CommandStatus; @IsOptional() @IsObject() response?:Record<string,unknown>; }
export class CameraMediaDto { @IsString() vehicleId!:string; @IsString() type!:string; @IsString() url!:string; @IsOptional() @IsString() thumbnailUrl?:string; @IsOptional() @IsInt() @Min(0) durationSeconds?:number; @IsDateString() capturedAt!:string; @IsOptional() @IsObject() metadata?:Record<string,unknown>; }
export class ConfigurationOptionDto { @IsString() category!:string; @IsString() label!:string; @IsString() value!:string; @IsOptional() @IsBoolean() active?:boolean; @IsOptional() @IsInt() sortOrder?:number; @IsOptional() @IsObject() metadata?:Record<string,unknown>; }
