import type { OpenAPIObject,OperationObject,SchemaObject } from "@nestjs/swagger";

export const swaggerTags=[
  ["System","Service health and operational status"],["Authentication","Login, session refresh, logout and current user"],["Vehicles","Vehicle master data and assignment"],["Telemetry","Normalized GPS positions and route history"],["Drivers","Driver records and vehicle relationships"],["Geofences","Geographic zones and geometry"],["Alerts","Fleet alerts, acknowledgement and resolution"],["Maintenance","Scheduled and completed maintenance"],["Fuel","Fuel purchases and consumption records"],["Tasks","Fleet jobs and delivery tasks"],["Device Commands","Commands queued for GPS devices"],["Cameras","Vehicle camera media metadata"],["Configuration","Organization dropdown values and system configuration"],["Users","Organization users and roles"],["Audit","Immutable administrative activity history"],["Reports","Dashboard, utilization and route analytics"],
] as const;

const tagFor=(path:string)=>path.includes("/health")?"System":path.includes("/auth/")?"Authentication":path.includes("/drivers")?"Drivers":path.includes("/positions")||path.includes("/history")?"Telemetry":path.includes("/vehicles")&&!path.includes("/reports/")?"Vehicles":path.includes("/geofences")?"Geofences":path.includes("/alerts")?"Alerts":path.includes("/maintenance")?"Maintenance":path.includes("/fuel")?"Fuel":path.includes("/tasks")?"Tasks":path.includes("/commands")?"Device Commands":path.includes("/cameras")?"Cameras":path.includes("/configuration-options")?"Configuration":path.includes("/users")?"Users":path.includes("/audit-logs")?"Audit":"Reports";
const methodLabel:Record<string,string>={get:"Retrieve",post:"Create / execute",patch:"Update",put:"Replace",delete:"Delete"};
const examples:Record<string,unknown>={
  "POST /v1/auth/login":{email:"admin@orbit.sa",password:"Orbit@2026"},
  "POST /v1/auth/refresh":{refreshToken:"eyJ..."},"POST /v1/auth/logout":{refreshToken:"eyJ..."},
  "POST /v1/vehicles":{name:"سيارة توزيع 01",plateNumber:"ABC 1234",vin:"WVWZZZ1JZXW000001",group:"أسطول الرياض",make:"Toyota",model:"Hilux",year:2025,color:"#ffffff"},
  "PATCH /v1/vehicles/{id}":{name:"سيارة توزيع 01 - محدثة",group:"أسطول جدة",driverId:"driver-id"},
  "POST /v1/vehicles/{id}/positions":{latitude:24.7136,longitude:46.6753,speed:73,heading:120,altitude:620,ignition:true,accuracy:5,recordedAt:"2026-08-17T11:00:00.000Z",raw:{source:"tcp-adapter"}},
  "POST /v1/drivers":{name:"خالد محمد",phone:"+966500000000",email:"driver@example.com",licenseNumber:"LIC-1001",licenseExpiresAt:"2028-12-31T00:00:00.000Z",active:true},
  "PATCH /v1/drivers/{id}":{name:"خالد محمد",phone:"+966511111111",licenseNumber:"LIC-1001",active:true},
  "POST /v1/geofences":{name:"مستودع الرياض",type:"circle",geometry:{center:{latitude:24.7136,longitude:46.6753},radiusMeters:1000},color:"#28e1da",active:true},
  "PATCH /v1/geofences/{id}":{name:"مستودع الرياض",type:"circle",geometry:{center:{latitude:24.7136,longitude:46.6753},radiusMeters:1500},color:"#28e1da",active:true},
  "POST /v1/alerts":{vehicleId:"vehicle-id",type:"OVERSPEED",title:"تجاوز السرعة",message:"تجاوزت المركبة السرعة المسموحة",severity:"WARNING",metadata:{limit:120,actual:132}},
  "PATCH /v1/alerts/{id}/status":{status:"ACKNOWLEDGED"},
  "POST /v1/maintenance":{vehicleId:"vehicle-id",name:"تغيير الزيت",description:"زيت وفلتر",status:"UPCOMING",intervalKm:10000,dueAt:"2026-09-01T00:00:00.000Z",dueOdometer:50000,cost:450},
  "PATCH /v1/maintenance/{id}":{vehicleId:"vehicle-id",name:"تغيير الزيت",status:"COMPLETED",cost:475},
  "POST /v1/fuel":{vehicleId:"vehicle-id",liters:42.5,pricePerLiter:2.33,totalCost:99.03,odometer:45220,station:"محطة الرياض",filledAt:"2026-08-17T10:00:00.000Z"},
  "POST /v1/tasks":{vehicleId:"vehicle-id",title:"توصيل شحنة",description:"من المستودع إلى الفرع",status:"NEW",priority:2,startsAt:"2026-08-18T08:00:00.000Z",dueAt:"2026-08-18T12:00:00.000Z"},
  "PATCH /v1/tasks/{id}":{title:"توصيل شحنة",status:"IN_PROGRESS",priority:2},
  "POST /v1/commands":{vehicleId:"vehicle-id",type:"REQUEST_POSITION",payload:{reason:"manual_refresh"}},
  "PATCH /v1/commands/{id}/status":{status:"ACKNOWLEDGED",response:{message:"OK"}},
  "POST /v1/cameras":{vehicleId:"vehicle-id",type:"front_snapshot",url:"https://cdn.example.com/media/image.jpg",thumbnailUrl:"https://cdn.example.com/media/thumb.jpg",capturedAt:"2026-08-17T10:00:00.000Z",metadata:{cameraPosition:"front"}},
  "POST /v1/configuration-options":{category:"vehicle_group",label:"أسطول الدمام",value:"dammam_fleet",active:true,sortOrder:10},
  "PATCH /v1/configuration-options/{id}":{category:"vehicle_group",label:"أسطول الدمام المحدث",value:"dammam_fleet",active:true,sortOrder:10},
  "POST /v1/users":{name:"مشرف العمليات",email:"ops@example.com",password:"StrongPassword123!",role:"DISPATCHER",active:true},
};

const schemas:Record<string,unknown>={
  LoginDto:{type:"object",required:["email","password"],properties:{email:{type:"string",format:"email",example:"admin@orbit.sa",description:"User email address"},password:{type:"string",format:"password",minLength:8,example:"Orbit@2026",description:"Account password"}}},
  RefreshDto:{type:"object",properties:{refreshToken:{type:"string",example:"eyJhbGciOiJIUzI1Ni...",description:"Refresh JWT; optional when the HttpOnly refresh cookie exists"}}},
  CreateVehicleDto:{type:"object",required:["name","plateNumber"],properties:{name:{type:"string",example:"سيارة توزيع 01"},plateNumber:{type:"string",example:"ABC 1234"},vin:{type:"string",example:"WVWZZZ1JZXW000001"},group:{type:"string",example:"أسطول الرياض"},make:{type:"string",example:"Toyota"},model:{type:"string",example:"Hilux"},year:{type:"integer",minimum:1980,maximum:2100,example:2025},color:{type:"string",example:"#ffffff"},driverId:{type:"string",example:"driver-id"}}},
  UpdateVehicleDto:{type:"object",properties:{name:{type:"string",example:"سيارة توزيع 01 - محدثة"},plateNumber:{type:"string",example:"ABC 1234"},vin:{type:"string"},group:{type:"string",example:"أسطول جدة"},make:{type:"string"},model:{type:"string"},year:{type:"integer",minimum:1980,maximum:2100},color:{type:"string"},driverId:{type:"string",nullable:true}}},
  PositionDto:{type:"object",required:["latitude","longitude","speed","heading","ignition","recordedAt"],properties:{latitude:{type:"number",format:"double",minimum:-90,maximum:90,example:24.7136},longitude:{type:"number",format:"double",minimum:-180,maximum:180,example:46.6753},speed:{type:"number",minimum:0,example:73,description:"Kilometers per hour"},heading:{type:"number",minimum:0,maximum:360,example:120},altitude:{type:"number",example:620},ignition:{type:"boolean",example:true},accuracy:{type:"number",minimum:0,example:5},recordedAt:{type:"string",format:"date-time",example:"2026-08-17T11:00:00.000Z"},raw:{type:"object",additionalProperties:true,example:{source:"tcp-adapter"}}}},
  CreateDriverDto:{type:"object",required:["name","licenseNumber"],properties:{name:{type:"string",example:"خالد محمد"},phone:{type:"string",example:"+966500000000"},email:{type:"string",format:"email",example:"driver@example.com"},licenseNumber:{type:"string",example:"LIC-1001"},licenseExpiresAt:{type:"string",format:"date-time",example:"2028-12-31T00:00:00.000Z"},active:{type:"boolean",default:true}}},
  UpdateDriverDto:{type:"object",properties:{name:{type:"string"},phone:{type:"string"},email:{type:"string",format:"email"},licenseNumber:{type:"string"},licenseExpiresAt:{type:"string",format:"date-time"},active:{type:"boolean"}}},
  GeofenceDto:{type:"object",required:["name","type","geometry"],properties:{name:{type:"string",example:"مستودع الرياض"},type:{type:"string",enum:["circle","polygon"],example:"circle"},geometry:{type:"object",additionalProperties:true,example:{center:{latitude:24.7136,longitude:46.6753},radiusMeters:1000}},color:{type:"string",default:"#28e1da"},active:{type:"boolean",default:true}}},
  AlertDto:{type:"object",required:["type","title","message"],properties:{vehicleId:{type:"string",example:"vehicle-id"},type:{type:"string",example:"OVERSPEED"},title:{type:"string",example:"تجاوز السرعة"},message:{type:"string",example:"تجاوزت المركبة السرعة المسموحة"},severity:{type:"string",enum:["INFO","WARNING","CRITICAL"],default:"INFO"},metadata:{type:"object",additionalProperties:true,example:{limit:120,actual:132}}}},
  AlertStatusDto:{type:"object",required:["status"],properties:{status:{type:"string",enum:["OPEN","ACKNOWLEDGED","RESOLVED"],example:"ACKNOWLEDGED"}}},
  MaintenanceDto:{type:"object",required:["vehicleId","name"],properties:{vehicleId:{type:"string"},name:{type:"string",example:"تغيير الزيت"},description:{type:"string"},status:{type:"string",enum:["UPCOMING","DUE","OVERDUE","COMPLETED"]},intervalKm:{type:"number",minimum:0},intervalHours:{type:"number",minimum:0},dueAt:{type:"string",format:"date-time"},dueOdometer:{type:"number",minimum:0},cost:{type:"number",minimum:0,example:450}}},
  FuelDto:{type:"object",required:["vehicleId","liters","filledAt"],properties:{vehicleId:{type:"string"},liters:{type:"number",minimum:0.01,example:42.5},pricePerLiter:{type:"number",minimum:0},totalCost:{type:"number",minimum:0},odometer:{type:"number",minimum:0},station:{type:"string",example:"محطة الرياض"},filledAt:{type:"string",format:"date-time"}}},
  TaskDto:{type:"object",required:["title"],properties:{title:{type:"string",example:"توصيل شحنة"},description:{type:"string"},vehicleId:{type:"string"},status:{type:"string",enum:["NEW","IN_PROGRESS","COMPLETED","FAILED","CANCELLED"]},priority:{type:"integer",minimum:1,maximum:4,default:2},startsAt:{type:"string",format:"date-time"},dueAt:{type:"string",format:"date-time"}}},
  UserDto:{type:"object",required:["name","email","password","role"],properties:{name:{type:"string",example:"مشرف العمليات"},email:{type:"string",format:"email",example:"ops@example.com"},password:{type:"string",format:"password",minLength:8,example:"StrongPassword123!"},role:{type:"string",enum:["SUPER_ADMIN","ADMIN","DISPATCHER","MANAGER","VIEWER"]},active:{type:"boolean",default:true}}},
  CommandDto:{type:"object",required:["vehicleId","type"],properties:{vehicleId:{type:"string"},type:{type:"string",example:"REQUEST_POSITION"},payload:{type:"object",additionalProperties:true,example:{reason:"manual_refresh"}}}},
  CommandStatusDto:{type:"object",required:["status"],properties:{status:{type:"string",enum:["PENDING","SENT","ACKNOWLEDGED","FAILED","CANCELLED"]},response:{type:"object",additionalProperties:true,example:{message:"OK"}}}},
  CameraMediaDto:{type:"object",required:["vehicleId","type","url","capturedAt"],properties:{vehicleId:{type:"string"},type:{type:"string",example:"front_snapshot"},url:{type:"string",format:"uri"},thumbnailUrl:{type:"string",format:"uri"},durationSeconds:{type:"integer",minimum:0},capturedAt:{type:"string",format:"date-time"},metadata:{type:"object",additionalProperties:true}}},
  ConfigurationOptionDto:{type:"object",required:["category","label","value"],properties:{category:{type:"string",example:"vehicle_group"},label:{type:"string",example:"أسطول الدمام"},value:{type:"string",example:"dammam_fleet"},active:{type:"boolean",default:true},sortOrder:{type:"integer",default:0},metadata:{type:"object",additionalProperties:true}}},
};

export function decorateOpenApi(document:OpenAPIObject){
  document.tags=swaggerTags.map(([name,description])=>({name,description}));
  document.components={...document.components,schemas:schemas as Record<string,SchemaObject>};
  for(const [path,pathItem] of Object.entries(document.paths))for(const method of ["get","post","patch","put","delete"]){const operation=(pathItem as Record<string,unknown>)[method] as OperationObject|undefined;if(!operation)continue;const tag=tagFor(path);operation.tags=[tag];operation.summary=operation.summary||`${methodLabel[method]} ${tag.toLowerCase()}`;operation.description=operation.description||`${methodLabel[method]} operation in the ${tag} module. Organization scope is enforced from the authenticated session.`;const key=`${method.toUpperCase()} ${path}`;const example=examples[key];if(example&&operation.requestBody){const body=operation.requestBody as {content?:Record<string,{example?:unknown;examples?:unknown}>};const json=body.content?.["application/json"];if(json){json.example=example;json.examples={complete:{summary:"Complete request example",value:example}};}}for(const parameter of operation.parameters??[]){if("name" in parameter){if(parameter.name==="page")parameter.example="1";if(parameter.name==="perPage")parameter.example="50";if(parameter.name==="search")parameter.example="";if(parameter.name==="from")parameter.example="2026-08-01T00:00:00.000Z";if(parameter.name==="to")parameter.example="2026-08-17T23:59:59.999Z";if(parameter.name==="status")parameter.example="OPEN";if(parameter.name==="includeInactive")parameter.example="true";}}operation.responses={...operation.responses,"400":{description:"Validation failed"},"401":{description:"Missing, invalid or expired authentication"},"403":{description:"Authenticated role is not permitted"},"404":{description:"Resource not found in the current organization"}};if(tag!=="System"&&!(tag==="Authentication"&&(path.endsWith("/login")||path.endsWith("/refresh"))))operation.security=[{bearerAuth:[]},{cookieAuth:[]}];}
  return document;
}
